import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, ArrowDown, X, Plus, Minus, ArrowCounterClockwise, Pause, Play } from '@phosphor-icons/react';
import '@fontsource-variable/inter';
import '@fontsource/caveat/400.css';
import { App as ExistingApp } from './App.jsx';
import './ink.css';
const asset = name => `${import.meta.env.BASE_URL}assets/${name}`;
const texts = {
 en: { nav:['About','Sundays','Community','Sermons'], visit:'Plan a visit', church:'FORDHAM COMMUNITY CHURCH', location:'THE BRONX, NEW YORK', hero:['A kingdom','family.'], script:'know. live. love.', deck:'Displaying the love of Jesus, together.', drag:'Drag the artwork to explore', reset:'Reset artwork', pause:'Pause motion', resume:'Resume motion', scroll:'A life rooted in Jesus', chapter:'THIS IS OUR LIFE TOGETHER', words:['Know','Live','Love'], chapters:[['Rooted in the Gospel.','We open the Scriptures to know God and the good news of Jesus. His death and resurrection are the beginning of our life together.','What we believe','beliefs'],['Faith around the table.','We follow Jesus in ordinary life. We share meals, carry burdens, pray for one another, and grow as a family.','Find your community','city-link'],['For our neighbors.','The love we have received becomes the love we give. We serve our neighbors in the Bronx in word and deed.','Meet our church','about']], intro:'A church of the Bronx.\nFor the Bronx.', introCopy:'Different stories. One Savior. A family being formed by God’s Word and sent to love the place we call home.', worship:'EVERY SUNDAY, TOGETHER', worshipTitle:['Come as you are.','Worship with us.'], worshipCopy:'We gather to sing, pray, open the Bible, and remember the good news of Jesus.', times:'Two languages. One family.', english:'English', es:'Español', address:'2439 Creston Avenue, Bronx, NY 10468', directions:'Get directions', next:'YOUR NEXT STEP', nextTitle:'There’s room to grow.', groups:['City Link groups','Life together, beyond Sunday.'], kids:['FCC Kids','Little people. Big Gospel.'], teachings:['Sermons','Return to the good news.'], happening:'IN THE LIFE OF OUR CHURCH', eventsTitle:'Coming together.', events:['Ecclesiastes','Membership classes','Men’s retreat'], eventNotes:['Explore our teaching','Take your next step','November 6–8'], end:'For Christ.\nFor the Bronx.', contact:'Start a conversation', give:'Give', back:'Back to top', dialogTitle:'See you Sunday.', dialogIntro:'Choose a service and find your way here. You don’t need to register to join us.', service:'Choose your service', close:'Close', faq:[['What should I expect?','Singing, prayer, and teaching from the Bible. Come as you are; you are welcome to listen and ask questions.'],['What about my children?','FCC Kids welcomes children from nursery through fifth grade. Our team can help you find the right classroom when you arrive.'],['How do I find you?','We meet at 2439 Creston Avenue in the Bronx. Use the directions link below to plan your route.']], details:'More about Sundays', skip:'Skip to content', prev:'Previous event', nextEvent:'Next event' },
 es: { nav:['Nosotros','Domingos','Comunidad','Sermones'], visit:'Planea tu visita', church:'FORDHAM COMMUNITY CHURCH', location:'EL BRONX, NUEVA YORK', hero:['Una familia','del Reino.'], script:'conocer. vivir. amar.', deck:'Mostrando el amor de Jesús, juntos.', drag:'Arrastra la ilustración para explorar', reset:'Restablecer ilustración', pause:'Pausar movimiento', resume:'Reanudar movimiento', scroll:'Una vida arraigada en Jesús', chapter:'NUESTRA VIDA JUNTOS', words:['Conocer','Vivir','Amar'], chapters:[['Arraigados en el Evangelio.','Abrimos las Escrituras para conocer a Dios y las buenas nuevas de Jesús. Su muerte y resurrección son el principio de nuestra vida juntos.','Lo que creemos','beliefs'],['La fe alrededor de la mesa.','Seguimos a Jesús en la vida cotidiana. Compartimos comidas, llevamos las cargas de otros, oramos y crecemos como familia.','Encuentra tu comunidad','city-link'],['Para nuestros vecinos.','El amor que hemos recibido se convierte en el amor que damos. Servimos a nuestros vecinos del Bronx de palabra y de hecho.','Conoce nuestra iglesia','about']], intro:'Una iglesia del Bronx.\nPara el Bronx.', introCopy:'Historias diferentes. Un Salvador. Una familia formada por la Palabra de Dios y enviada a amar el lugar que llamamos hogar.', worship:'CADA DOMINGO, JUNTOS', worshipTitle:['Ven tal como eres.','Adora con nosotros.'], worshipCopy:'Nos reunimos para cantar, orar, abrir la Biblia y recordar las buenas nuevas de Jesús.', times:'Dos idiomas. Una familia.', english:'Inglés', es:'Español', address:'2439 Creston Avenue, Bronx, NY 10468', directions:'Cómo llegar', next:'TU PRÓXIMO PASO', nextTitle:'Hay espacio para crecer.', groups:['Grupos City Link','Vida juntos, más allá del domingo.'], kids:['FCC Kids','Personas pequeñas. Gran Evangelio.'], teachings:['Sermones','Vuelve a las buenas nuevas.'], happening:'EN LA VIDA DE NUESTRA IGLESIA', eventsTitle:'Nos reunimos.', events:['Eclesiastés','Clases de membresía','Retiro de hombres'], eventNotes:['Explora nuestras enseñanzas','Da tu próximo paso','6–8 de noviembre'], end:'Para Cristo.\nPara el Bronx.', contact:'Inicia una conversación', give:'Dar', back:'Volver arriba', dialogTitle:'Nos vemos el domingo.', dialogIntro:'Elige un servicio y encuentra cómo llegar. No necesitas inscribirte para acompañarnos.', service:'Elige tu servicio', close:'Cerrar', faq:[['¿Qué puedo esperar?','Cantos, oración y enseñanza de la Biblia. Ven tal como eres; puedes escuchar y hacer preguntas.'],['¿Y mis hijos?','FCC Kids recibe a niños desde la cuna hasta quinto grado. Nuestro equipo te ayudará a encontrar el salón adecuado.'],['¿Cómo los encuentro?','Nos reunimos en 2439 Creston Avenue, en el Bronx. Usa el enlace de indicaciones para planear tu ruta.']], details:'Más sobre los domingos', skip:'Ir al contenido', prev:'Evento anterior', nextEvent:'Próximo evento' }
};
const maps='https://www.google.com/maps/dir/?api=1&destination=2439+Creston+Avenue+Bronx+NY+10468';
function useReducedMotion() {const [value,set]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const fn=()=>set(q.matches);q.addEventListener('change',fn);return()=>q.removeEventListener('change',fn)},[]);return value;}
function InkScene({t,paused}) {
 const scene=useRef(null), rot=useRef({x:0,y:0,tx:0,ty:0}), drag=useRef(null);const reduced=useReducedMotion();
 useEffect(()=>{if(paused||reduced){scene.current?.style.setProperty('--rx','0deg');scene.current?.style.setProperty('--ry','0deg');return;}let frame=0,visible=true;const tick=()=>{frame=0;const r=rot.current;r.x+=(r.tx-r.x)*.09;r.y+=(r.ty-r.y)*.09;scene.current?.style.setProperty('--rx',`${r.x}deg`);scene.current?.style.setProperty('--ry',`${r.y}deg`);if(visible&&(Math.abs(r.tx-r.x)+Math.abs(r.ty-r.y)>.01))frame=requestAnimationFrame(tick)};const wake=()=>{if(!frame&&visible)frame=requestAnimationFrame(tick)};const el=scene.current;el.addEventListener('pointermove',wake);el.addEventListener('keydown',wake);el.addEventListener('click',wake);const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;el.classList.toggle('is-paused',!visible);if(visible)wake();else cancelAnimationFrame(frame)},{threshold:0});observer.observe(el);return()=>{cancelAnimationFrame(frame);observer.disconnect();el.removeEventListener('pointermove',wake);el.removeEventListener('keydown',wake);el.removeEventListener('click',wake)}},[paused,reduced]);
 const reset=()=>{rot.current.tx=0;rot.current.ty=0;};
 return <div className={`ink-scene ${paused?'is-paused':''}`} ref={scene}>
  <div className="ink-collage" role="button" tabIndex={0} aria-label={t.drag} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','Enter',' '].includes(e.key)){e.preventDefault();if(['Home','Enter',' '].includes(e.key))reset();else {rot.current.ty=Math.max(-24,Math.min(24,rot.current.ty+(e.key==='ArrowRight'?8:e.key==='ArrowLeft'?-8:0)));rot.current.tx=Math.max(-14,Math.min(14,rot.current.tx+(e.key==='ArrowUp'?8:e.key==='ArrowDown'?-8:0)));}}}}
  onPointerDown={e=>{if(paused||reduced)return;drag.current={x:e.clientX,y:e.clientY,rx:rot.current.tx,ry:rot.current.ty};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current||paused||reduced)return;rot.current.ty=Math.max(-24,Math.min(24,drag.current.ry+(e.clientX-drag.current.x)*.12));rot.current.tx=Math.max(-14,Math.min(14,drag.current.rx-(e.clientY-drag.current.y)*.08));}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}>
   <div className="collage-plane"><img className="scene-tree" src={asset('tree-art.webp')} alt="" fetchPriority="high" draggable="false"/><img className="scene-branch" src={asset('branch-ink.png')} alt="" draggable="false"/><img className="scene-tomb" src={asset('tomb-art.webp')} alt="" draggable="false"/><span className="scene-note">{t.script}</span></div>
  </div>
  <div className="scene-tools"><span>{t.drag}</span><button onClick={reset} aria-label={t.reset}><ArrowCounterClockwise size={18}/></button></div>
 </div>
}
function SundayDialog({open,onClose,t}) {
 const ref=useRef(null);const [service,setService]=useState('es');const [faq,setFaq]=useState(-1);
 useEffect(()=>{const el=ref.current;if(open){el.showModal();document.body.style.overflow='hidden';}else if(el.open)el.close();return()=>{document.body.style.overflow='';}},[open]);
 return <dialog ref={ref} className="sunday-dialog" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}} onClose={onClose}><div className="sunday-dialog-inner"><div className="dialog-top"><span>FCC · {t.nav[1]}</span><button autoFocus onClick={onClose} aria-label={t.close}><X size={24}/></button></div><h2>{t.dialogTitle}</h2><p>{t.dialogIntro}</p><fieldset><legend>{t.service}</legend><div className="service-options">{['es','en'].map(code=><label key={code} className={service===code?'selected':''}><input type="radio" name="service" value={code} checked={service===code} onChange={()=>setService(code)}/><span>{code==='es'?t.es:t.english}</span><strong>{code==='es'?'9:45':'11:45'} <small>AM</small></strong></label>)}</div></fieldset><address>{t.address}</address><a className="solid-button" href={maps} target="_blank" rel="noreferrer">{t.directions}<ArrowUpRight size={19}/></a><div className="sunday-faq">{t.faq.map(([q,a],i)=><div key={q}><button aria-expanded={faq===i} aria-controls={`answer-${i}`} onClick={()=>setFaq(faq===i?-1:i)}>{q}{faq===i?<Minus size={18}/>:<Plus size={18}/>}</button><p id={`answer-${i}`} hidden={faq!==i}>{a}</p></div>)}</div><a className="text-link" href="#/sundays" onClick={onClose}>{t.details}<ArrowRight size={18}/></a></div></dialog>
}
function Home({lang,setLang}) {
 const t=texts[lang], reduced=useReducedMotion();const [paused,setPaused]=useState(false),[visit,setVisit]=useState(false),[chapter,setChapter]=useState(0);const hero=useRef(null),film=useRef(null),root=useRef(null),events=useRef(null);const [eventIndex,setEventIndex]=useState(0);
 useEffect(()=>{document.title='Fordham Community Church · The Bronx';let frame=0;const update=()=>{frame=0;if(!root.current)return;const h=hero.current?.getBoundingClientRect();const p=h?Math.min(1,Math.max(0,-h.top/Math.max(1,h.height-innerHeight))):0;root.current.style.setProperty('--hero-progress',reduced||paused?'0':p.toFixed(4));const f=film.current?.getBoundingClientRect();root.current.style.setProperty('--film-progress',reduced||paused?'1':Math.min(1,Math.max(0,(innerHeight-(f?.top??0))/(innerHeight*.9))).toFixed(4));};const sync=()=>{if(!frame)frame=requestAnimationFrame(update)};window.addEventListener('scroll',sync,{passive:true});window.addEventListener('resize',sync);update();const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');obs.unobserve(e.target)}}),{threshold:.12});root.current.querySelectorAll('[data-enter]').forEach(el=>obs.observe(el));return()=>{cancelAnimationFrame(frame);obs.disconnect();window.removeEventListener('scroll',sync);window.removeEventListener('resize',sync)}},[reduced,paused]);
 const links=[['about','About'],['sundays','Sundays'],['connect','Community'],['sermons','Sermons']];
 const moveEvent=(delta)=>{const el=events.current;const next=Math.max(0,Math.min(2,eventIndex+delta));const card=el?.children[next];if(card)el.scrollTo({left:card.offsetLeft-el.children[0].offsetLeft,behavior:reduced?'instant':'smooth'});};
 return <div className={`ink-app ${paused?'motion-paused':''}`} ref={root}>
  <a className="skip-link" href="#main-content">{t.skip}</a>
  <header className="ink-header"><a href="#top" className="ink-logo" aria-label="Fordham Community Church home"><img src={asset('fcc-mark.png')} alt="FCC"/></a><nav aria-label={lang==='es'?'Principal':'Primary'}>{links.map(([id],i)=><a key={id} href={id==='sermons'?'#/sermons':`#${id}`}>{t.nav[i]}</a>)}</nav><div className="ink-header-actions"><div className="language-switch" role="group" aria-label={lang==='es'?'Idioma':'Language'}>{['en','es'].map(code=><button key={code} aria-pressed={lang===code} onClick={()=>setLang(code)}>{code.toUpperCase()}</button>)}</div><button className="visit-header" onClick={()=>setVisit(true)}>{t.visit}<ArrowUpRight size={16}/></button></div></header>
  <main id="main-content">
   <section className="ink-hero" id="top" ref={hero}><div className="hero-sticky"><div className="hero-topline"><span>{t.church}</span><span>{t.location}</span></div><div className="hero-composition"><h1 id="hero-title">{t.hero[0]}<br/><span>{t.hero[1]}</span></h1><InkScene t={t} paused={paused}/><p className="hero-caption">{t.deck}</p></div><div className="hero-bottom"><a href="#about">{t.scroll}<ArrowDown size={20}/></a><button className="motion-toggle" onClick={()=>setPaused(!paused)} aria-label={paused?t.resume:t.pause} aria-pressed={paused}>{paused?<Play size={17}/>:<Pause size={17}/>}</button><button className="hero-visit" onClick={()=>setVisit(true)}>{t.visit}<ArrowUpRight size={20}/></button></div></div></section>
   <section className="ink-intro" id="about"><p className="micro" data-enter>{t.chapter}</p><h2 data-enter>{t.intro.split('\n').map(line=><span key={line}>{line}</span>)}</h2><p className="intro-body" data-enter>{t.introCopy}</p><a className="text-link" href="#/about">{t.nav[0]}<ArrowUpRight size={20}/></a></section>
   <section className="chapter-section" aria-label={t.chapter}><div className="chapter-tabs" role="tablist" aria-label={t.chapter}>{t.words.map((word,i)=><button role="tab" id={`tab-${i}`} aria-selected={chapter===i} aria-controls={`chapter-${i}`} tabIndex={chapter===i?0:-1} key={word} onClick={()=>setChapter(i)} onKeyDown={e=>{const next=e.key==='ArrowRight'?(i+1)%3:e.key==='ArrowLeft'?(i+2)%3:e.key==='Home'?0:e.key==='End'?2:null;if(next!==null){e.preventDefault();setChapter(next);document.getElementById(`tab-${next}`)?.focus()}}}><small>0{i+1}</small>{word}<span className="tab-dot"/></button>)}</div><div className="chapter-body" role="tabpanel" id={`chapter-${chapter}`} aria-labelledby={`tab-${chapter}`} key={`${chapter}-${lang}`}><div className="chapter-art"><img src={asset(['tomb-art.webp','communion-art.webp','flower-ink.jpg'][chapter])} alt="" loading="lazy"/></div><div className="chapter-copy"><span className="script">{t.words[chapter].toLowerCase()}.</span><h3>{t.chapters[chapter][0]}</h3><p>{t.chapters[chapter][1]}</p><a className="text-link" href={`#/${t.chapters[chapter][3]}`}>{t.chapters[chapter][2]}<ArrowUpRight size={20}/></a></div></div></section>
   <section className="sunday-section" id="sundays"><div className="sunday-heading" data-enter><p className="micro">{t.worship}</p><h2>{t.worshipTitle[0]}<br/><span className="script">{t.worshipTitle[1]}</span></h2></div><div className="worship-film" ref={film}><img src={asset('fcc-worship.webp')} alt={lang==='es'?'Equipo de adoración de Fordham Community Church':'Fordham Community Church worship team'} loading="lazy"/><button className="film-cta" onClick={()=>setVisit(true)}>{t.visit}<ArrowUpRight size={22}/></button><span className="film-caption">{t.church} · {t.nav[1]}</span></div><div className="sunday-information"><div><h3>{t.times}</h3><p>{t.worshipCopy}</p></div><div className="sunday-times"><button onClick={()=>setVisit(true)}><span>{t.es}</span><strong>9:45 <small>AM</small></strong><ArrowUpRight size={20}/></button><button onClick={()=>setVisit(true)}><span>{t.english}</span><strong>11:45 <small>AM</small></strong><ArrowUpRight size={20}/></button><a href={maps} target="_blank" rel="noreferrer">{t.address}<ArrowUpRight size={18}/></a></div></div></section>
   <section className="next-section" id="connect"><div className="next-heading" data-enter><p className="micro">{t.next}</p><h2>{t.nextTitle}</h2></div><div className="next-list">{[t.groups,t.kids,t.teachings].map(([title,desc],i)=><a href={`#/${['city-link','fcc-kids','sermons'][i]}`} key={title}><span className="next-number">0{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div><div className="next-art"><img src={asset(['communion-art.webp','flower-ink.jpg','tomb-art.webp'][i])} alt="" loading="lazy"/></div><ArrowUpRight size={32} weight="light"/></a>)}</div></section>
   <section className="events-section"><div className="events-heading"><div><p className="micro">{t.happening}</p><h2>{t.eventsTitle}</h2></div><div className="event-controls"><button onClick={()=>moveEvent(-1)} disabled={eventIndex===0} aria-label={t.prev}><ArrowRight size={22} style={{transform:'rotate(180deg)'}}/></button><button onClick={()=>moveEvent(1)} disabled={eventIndex===2} aria-label={t.nextEvent}><ArrowRight size={22}/></button></div></div><div className="events-track" ref={events} onScroll={e=>{const el=e.currentTarget;setEventIndex(Math.min(2,Math.round(el.scrollLeft/(el.children[1]?.offsetLeft-el.children[0]?.offsetLeft||1))))}}>{['ecclesiastes.jpg','membership.jpg','retreat.jpg'].map((name,i)=><a className="event-card" key={name} href={`#/${i===0?'sermons':'contact'}`}><div><img src={asset(name)} alt={t.events[i]} loading="lazy"/></div><span><strong>{t.events[i]}</strong><ArrowUpRight size={21}/></span><p>{t.eventNotes[i]}</p></a>)}</div></section>
  </main>
  <footer className="ink-footer"><div className="footer-topline"><img src={asset('fcc-mark.png')} alt="FCC"/><span>{t.church}</span><a href="#top" aria-label={t.back}><ArrowUpRight size={24}/></a></div><h2>{t.end.split('\n').map(line=><span key={line}>{line}</span>)}</h2><div className="footer-bottom"><address>{t.address}</address><a href="#/contact">{t.contact}<ArrowUpRight size={18}/></a><a href="#/give">{t.give}<ArrowUpRight size={18}/></a><span>© {new Date().getFullYear()} FCC</span></div></footer>
  <SundayDialog open={visit} onClose={()=>setVisit(false)} t={t}/>
 </div>
}
export function InkApp(){const [route,setRoute]=useState(location.hash.startsWith('#/'));const [lang,setLang]=useState(()=>{try{return localStorage.getItem('fcc-language')==='es'?'es':'en'}catch{return'en'}});useEffect(()=>{const fn=()=>setRoute(location.hash.startsWith('#/'));window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);useEffect(()=>{document.documentElement.lang=lang;try{localStorage.setItem('fcc-language',lang)}catch{}},[lang]);return route?<ExistingApp/>:<Home lang={lang} setLang={setLang}/>}
